### ISSUE TITLE
Movie not playing in 1.0.4

### ISSUE THREAD

**Issue by emoose** [Lyall/AISomniumFiles2Fix#6]
Hi, thanks a lot for the fix, it's too bad that some developers are still relying on fans to fix their games...

I had an issue with one of the first movies game tries to play when entering Somnium for first time, there's meant to be a short ~5 second animation/movie (https://www.youtube.com/watch?v=JzZ2SA2nC6M&t=402s), but with 1.0.4 it just freezes with a black screen, MelonLoader console mentions "Video aspect ratio set to FitVertically." but that's all that happens.

Tried changing options in .cfg but nothing seemed to fix it, but downgrading to 1.0.3 does seem to let it work fine for me.

Screen res is 2560x1440 if that matters at all.

**Comment by Lyall** [comment]
Wait is that the actual emoose? You're work is awesome. 

Yes it definitely seems like I broke this in the latest release. I had added a part to address video scaling to see if that would affect a certain sequence that ends up being stretched at wider than native aspects but clearly did not test it properly.  I've implemented a proper fix for the video scaling now in release v1.0.5 so hopefully it should rectify this issue.

**Comment by emoose** [comment]
Thanks for the quick reply! Unfortunately seems the issue is still there for me with 1.0.5 though :(

In case it helps at all here's a save right before the bit that plays that video (hopefully game lets you share savegames... this is from `AppData\Local\SpikeChunsoft\AI Nirvana Initiative` dir):
[AI Nirvana Initiative.zip](https://github.com/Lyall/AISomniumFiles2Fix/files/9168983/AI.Nirvana.Initiative.zip)
The autosave with that should try loading the vid after the story-reminder part.

**Comment by Lyall** [comment]
> E: oh hmm, I noticed the console window still mentions AISomniumFiles2Fix v1.0.1 with that release, but your last commit should have changed that to 1.0.5? maybe github releases messed up somehow? E2: ah maybe not, ILSpy does seem to show the new `FixVideoAspectRatio` code there.

That's my bad, I ran the build before doing a quick version bump and didn't rebuild it. It's just that one line with the version number that changed.

That save is great, thanks for providing that. I can easily replicate the issue on my end now. I'll see if I can find out what's causing it and report back.

**Comment by Lyall** [comment]
Alright, fingers crossed this is it. Are you able to give this build a try?

[AISomniumFiles2Fix_v1.0.6.zip](https://github.com/Lyall/AISomniumFiles2Fix/files/9169305/AISomniumFiles2Fix_v1.0.6.zip)

**Comment by emoose** [comment]
Aha looks like it's working fine now! Many thanks for looking into it, and the quick fix too :)

**Comment by Lyall** [comment]
> Aha looks like it's working fine now! Many thanks for looking into it, and the quick fix too :)

Awesome, glad to hear it's working. Thank you for the report btw, I've been so busy with other stuff that it would have taken me far longer to notice this if you hadn't reported it.
